import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './Header'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

/* export const metadata: Metadata = {
  title: 'Mikkels Next.js App',
  description: 'Generated by create next app',
} */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head>
        <title>Mikkels Next.js App</title>
      </head>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
